#!/bin/sh
# script will generate "random" root password, displays it in the console, 
# and remove itself from startup

### BEGIN INIT INFO
# Provides:          set_root_password
# Required-Start:    $syslog
# Required-Stop:
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: set_root_password
# Description:       generates root password, logs it to console and syslog
### END INIT INFO

echo ""
echo "set-root-password: ****************************"
echo "set-root-password: Generating root password..."

# Generate very pseudo random string based on current time
HASH=`date +%s | sha256sum | base64`

# Strip confusing characters from the actual password
# no longer needed,ince we are using only lower case chars, 
# but can't hurt much to leave it there
PASS=`echo $HASH | sed 's/[1lO08B]//' | head -c 4 | tr [:upper:] [:lower:]`

echo "set-root-password: Setting root password..."
echo root:$PASS | chpasswd
chage -d 0 root

logger "set-root-password: **************************************"
logger "set-root-password: root password changed to     $PASS    "

echo "set-root-password: ****************************"
echo "set-root-password: root password:     $PASS    "
echo "set-root-password: ****************************"
echo ""

#sleep 1

#rm -f `/etc/rc2.d/basename $0`
update-rc.d -f set_root_password remove &>/dev/null

logger "set-root-password: removed self from startup scripts"
logger "set-root-password: **************************************"

